version: '3.7'

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=abc123!
      - MYSQL_DATABASE=membership

volumes:
  mysql-data: