// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"github.com/google/wire"
	"itmrchow/go-project/user/src/infrastructure/database"
	"itmrchow/go-project/user/src/interfaces/api/controllers"
	"itmrchow/go-project/user/src/interfaces/repo_impl"
	"itmrchow/go-project/user/src/usecase/repo"
)

// Injectors from wire.go:

func InitUserController() (*controllers.UserController, error) {
	mysqlHandler, err := database.NewMySqlHandler()
	if err != nil {
		return nil, err
	}
	userController := controllers.NewUserController(mysqlHandler)
	return userController, nil
}

// wire.go:

var dbSet = wire.NewSet(database.NewMySqlHandler)

var repoSet = wire.NewSet(repo_impl.NewUserRepoImpl, wire.Bind(new(repo.UserRepo), new(repo_impl.UserRepoImpl)))

var controllerSet = wire.NewSet(controllers.NewUserController)

var usecaseSet = wire.NewSet()
