definitions:
  reqdto.CreateUserReq:
    properties:
      account:
        example: jeff7777
        maxLength: 20
        minLength: 8
        type: string
      email:
        example: jeff@gmail.com
        type: string
      password:
        example: password
        maxLength: 20
        minLength: 8
        type: string
      phone:
        example: "+886955555555"
        type: string
      userName:
        description: 使用者名稱
        example: Jeff
        maxLength: 20
        minLength: 4
        type: string
    required:
    - account
    - email
    - password
    - phone
    - userName
    type: object
  reqdto.CreateWalletReq:
    properties:
      balance:
        example: 0
        type: number
      currency:
        example: PHP
        type: string
      userId:
        example: Jeff
        type: string
      walletType:
        example: P
        type: string
    type: object
  reqdto.DeductionReq:
    properties:
      amount:
        example: 50
        type: number
      description:
        example: 幫你扣個錢
        type: string
      eventName:
        example: Deduction
        type: string
      walletId:
        example: 12
        type: integer
    type: object
  reqdto.LoginReq:
    properties:
      account:
        example: jeff7777
        type: string
      email:
        example: jeff@gmail.com
        type: string
      password:
        example: password
        maxLength: 20
        minLength: 8
        type: string
    required:
    - password
    type: object
  reqdto.PatchUserReq:
    properties:
      account:
        example: jeff7777
        type: string
      email:
        example: jeff@gmail.com
        type: string
      password:
        example: jeffpwd
        type: string
      phone:
        example: "+886955555555"
        type: string
      userName:
        example: Jeff
        type: string
    type: object
  reqdto.PutUserReq:
    properties:
      account:
        example: jeff7777
        type: string
      email:
        example: jeff@gmail.com
        type: string
      password:
        example: jeffpwd
        type: string
      phone:
        example: "+886955555555"
        type: string
      userName:
        example: Jeff
        type: string
    type: object
  reqdto.TransferFundsReq:
    properties:
      amount:
        example: 100
        type: number
      description:
        example: Transfer Funds
        type: string
      fromWalletInfo:
        $ref: '#/definitions/reqdto.WalletInfoReq'
      toWalletInfo:
        $ref: '#/definitions/reqdto.WalletInfoReq'
    type: object
  reqdto.WalletInfoReq:
    properties:
      account:
        example: 1234567890
        type: integer
      userId:
        example: "1234567890"
        type: string
      walletType:
        type: string
    type: object
  respdto.ApiErrorResp:
    properties:
      detail:
        description: 問題描述
        type: string
      title:
        description: |-
          Type     string `json:"type,omitempty"`
          Status   int    `json:"status,omitempty"`   // http status
        type: string
    type: object
  respdto.CreateUserResp:
    properties:
      account:
        type: string
      email:
        type: string
      id:
        type: string
      phone:
        type: string
      userName:
        type: string
    type: object
  respdto.CreateWalletResp:
    properties:
      WalletType:
        example: P
        type: string
      balance:
        description: 餘額
        example: 0
        type: number
      createdAt:
        type: string
      createdBy:
        example: Jeff
        type: string
      currency:
        description: 幣別
        example: PHP
        type: string
      updatedAt:
        type: string
      updatedBy:
        example: Jeff
        type: string
      userId:
        example: Jeff
        type: string
    type: object
  respdto.FindWalletResp:
    properties:
      WalletType:
        type: string
      balance:
        description: 餘額
        type: number
      createdAt:
        type: string
      createdBy:
        type: string
      currency:
        description: 幣別
        type: string
      updatedAt:
        type: string
      updatedBy:
        type: string
      userId:
        type: string
    type: object
  respdto.GetWalletResp:
    properties:
      WalletType:
        type: string
      balance:
        description: 餘額
        type: number
      createdAt:
        type: string
      createdBy:
        type: string
      currency:
        description: 幣別
        type: string
      updatedAt:
        type: string
      updatedBy:
        type: string
      userId:
        type: string
    type: object
  respdto.LoginResp:
    properties:
      exp:
        example: 1719218836
        type: integer
      token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50IjoiamVmZjc3NzciLCJlbWFpbCI6ImplZmZAZ21haWwuY29tIiwiZXhwIjoxNzE5MjE4ODM2LCJpZCI6ImZhNzkxODE2LWRkMzUtNDJlNi1hNDc1LTAwZjg3ZDRhYzlhYSIsInBob25lIjoiKzg4Njk1NTU1NTU1NSIsInVzZXJOYW1lIjoiSmVmZiJ9.ALccbWnDW4Tg6NvIS8aCw3B96okQ3gLVqiEz3Ukq_eA
        type: string
    type: object
info:
  contact: {}
  description: User Service API
  title: User Service API
  version: "1.0"
paths:
  /deduction:
    post:
      parameters:
      - description: TransferFunds sample
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/reqdto.DeductionReq'
      produces:
      - application/json
      responses:
        "200":
          description: 返回成功
          schema:
            type: string
        default:
          description: error response
          schema:
            $ref: '#/definitions/respdto.ApiErrorResp'
      summary: 扣款
      tags:
      - Wallet
  /helloworld:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: HelloWorld example
      tags:
      - Example
  /login:
    post:
      parameters:
      - description: Login sample , account 和 email 需擇一輸入
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/reqdto.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: 返回token訊息
          schema:
            $ref: '#/definitions/respdto.LoginResp'
        default:
          description: error response
          schema:
            $ref: '#/definitions/respdto.ApiErrorResp'
      summary: 登入
      tags:
      - User
  /ping:
    get:
      consumes:
      - application/json
      description: 確認服務正常
      produces:
      - application/json
      responses:
        "200":
          description: pong
          schema:
            type: string
        default:
          description: error response
          schema:
            $ref: '#/definitions/respdto.ApiErrorResp'
      summary: Ping Server
      tags:
      - Example
  /transferfunds:
    post:
      parameters:
      - description: TransferFunds sample
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/reqdto.TransferFundsReq'
      produces:
      - application/json
      responses:
        "200":
          description: 返回成功
          schema:
            type: string
        default:
          description: error response
          schema:
            $ref: '#/definitions/respdto.ApiErrorResp'
      summary: 轉帳
      tags:
      - Wallet
  /user:
    post:
      parameters:
      - description: Create user sample
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/reqdto.CreateUserReq'
      produces:
      - application/json
      responses:
        "200":
          description: 返回創建用戶訊息
          schema:
            $ref: '#/definitions/respdto.CreateUserResp'
        default:
          description: error response
          schema:
            $ref: '#/definitions/respdto.ApiErrorResp'
      summary: 建立用戶
      tags:
      - User
  /user/{userId}:
    delete:
      parameters:
      - description: User Id
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok" "返回用户信息
          schema:
            type: string
        "400":
          description: err_code：10002 参数错误； err_code：10003 校验错误
          schema:
            type: string
        "401":
          description: err_code：10001 登录失败
          schema:
            type: string
      summary: 刪除用戶 by Id
      tags:
      - User
    get:
      parameters:
      - description: User Id
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok" "返回用户信息
          schema:
            type: string
        "400":
          description: err_code：10002 参数错误； err_code：10003 校验错误
          schema:
            type: string
        "401":
          description: err_code：10001 登录失败
          schema:
            type: string
      summary: 查詢用戶 by Id
      tags:
      - User
    patch:
      parameters:
      - description: User Id
        in: path
        name: userId
        required: true
        type: string
      - description: Patch user sample
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/reqdto.PatchUserReq'
      produces:
      - application/json
      responses:
        "200":
          description: ok" "返回用户信息
          schema:
            type: string
        "400":
          description: err_code：10002 参数错误； err_code：10003 校验错误
          schema:
            type: string
        "401":
          description: err_code：10001 登录失败
          schema:
            type: string
      summary: 部分更新用戶 by Id
      tags:
      - User
    put:
      parameters:
      - description: User Id
        in: path
        name: userId
        required: true
        type: string
      - description: Put user sample
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/reqdto.PutUserReq'
      produces:
      - application/json
      responses:
        "200":
          description: ok" "返回用户信息
          schema:
            type: string
        "400":
          description: err_code：10002 参数错误； err_code：10003 校验错误
          schema:
            type: string
        "401":
          description: err_code：10001 登录失败
          schema:
            type: string
      summary: 完整更新用戶 by Id
      tags:
      - User
  /users:
    get:
      parameters:
      - description: User Name
        in: query
        name: userName
        type: string
      - description: User Email
        in: query
        name: email
        type: string
      - description: User Phone
        in: query
        name: phone
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok" "返回用户信息
          schema:
            type: string
        "400":
          description: err_code：10002 参数错误； err_code：10003 校验错误
          schema:
            type: string
        "401":
          description: err_code：10001 登录失败
          schema:
            type: string
      summary: 查詢用戶
      tags:
      - User
  /wallet:
    post:
      parameters:
      - description: Create wallet sample
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/reqdto.CreateWalletReq'
      produces:
      - application/json
      responses:
        "200":
          description: 返回建立錢包訊息
          schema:
            $ref: '#/definitions/respdto.CreateWalletResp'
        default:
          description: error response
          schema:
            $ref: '#/definitions/respdto.ApiErrorResp'
      summary: 建立錢包
      tags:
      - Wallet
  /wallet/{userId}/{walletType}:
    get:
      parameters:
      - description: User Id
        in: path
        name: userId
        required: true
        type: string
      - description: Wallet Type
        in: path
        name: walletType
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 返回錢包訊息
          schema:
            $ref: '#/definitions/respdto.GetWalletResp'
        default:
          description: error response
          schema:
            $ref: '#/definitions/respdto.ApiErrorResp'
      summary: 取得錢包
      tags:
      - Wallet
  /wallets:
    get:
      description: '"查找User所屬的錢包"'
      parameters:
      - description: 錢包類型
        enum:
        - P
        in: query
        name: walletType
        type: string
      - description: 幣別
        enum:
        - PHP
        - USD
        - BTC
        - USDT
        in: query
        name: currency
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok" "返回錢包查詢訊息
          schema:
            items:
              $ref: '#/definitions/respdto.FindWalletResp'
            type: array
        default:
          description: error response
          schema:
            $ref: '#/definitions/respdto.ApiErrorResp'
      summary: 查詢錢包
      tags:
      - Wallet
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
tags:
- description: User API
  name: User
- description: Example API
  name: Example
- description: Wallet API
  name: Wallet
- description: Other description
  name: Other
